#!/bin/busybox sh
# HUT OS installer — GRUB BIOS installation

. "$HUTOS_INSTALL_LIB/common.sh"

install_grub_bios() {
	disk="$1"
	root_spec="$2"   # PARTUUID=... or /dev/...
	dst="$HUTOS_TARGET_MNT"

	is_whole_disk "$disk" || die "GRUB must be installed to a whole disk, got: $disk"
	[ -d "$dst/boot" ] || die "missing $dst/boot"

	require_cmd grub-install

	info "Installing GRUB (i386-pc) to $disk ..."

	export GRUB_DISABLE_OS_PROBER=true

	grub-install \
		--target=i386-pc \
		--directory=/usr/lib/grub/i386-pc \
		--boot-directory="$dst/boot" \
		--recheck \
		"$disk" >/tmp/hutos-grub-install.log 2>&1 \
		|| die "grub-install failed (see /tmp/hutos-grub-install.log)"

	mkdir -p "$dst/boot/grub"

	# GRUB search hint
	search_cmd="set root=(hd0,msdos1)"
	case "$root_spec" in
		PARTUUID=*)
			pu=$(echo "$root_spec" | sed 's/^PARTUUID=//')
			# GRUB can search by file UUID; for PARTUUID use device + linux root=
			search_cmd="set root=(hd0,msdos1)"
			;;
		UUID=*)
			uid=$(echo "$root_spec" | sed 's/^UUID=//')
			search_cmd="search --no-floppy --fs-uuid --set=root $uid"
			;;
	esac

	cat > "$dst/boot/grub/grub.cfg" <<EOF
# HUT OS GRUB configuration — generated by hut-install
set timeout=3
set default=0

menuentry "HUT OS (Hamedan University of Technology)" {
	insmod ext2
	insmod part_msdos
	$search_cmd
	linux /boot/vmlinuz root=$root_spec rw rootwait console=tty0 console=ttyS0 init=/init
}

menuentry "HUT OS (serial console)" {
	insmod ext2
	insmod part_msdos
	$search_cmd
	linux /boot/vmlinuz root=$root_spec rw rootwait console=ttyS0 init=/init
}
EOF

	sync
	ok "GRUB installed on $disk"
}
