#!/bin/busybox sh
# HUT OS installer — configuration for installed system

. "$HUTOS_INSTALL_LIB/common.sh"

install_write_config() {
	dst="$HUTOS_TARGET_MNT"
	part="$1"
	uuid="$2"
	hostname="$3"
	root_hash="$4"
	username="$5"
	user_hash="$6"
	partuuid="${7:-}"

	[ -d "$dst" ] || die "target not mounted"

	info "Writing system configuration..."

	echo "$hostname" > "$dst/etc/hostname"

	cat > "$dst/etc/hosts" <<EOF
127.0.0.1	localhost
127.0.1.1	$hostname

::1		localhost ip6-localhost ip6-loopback
EOF

	# fstab — UUID is fine for userspace
	if [ -n "$uuid" ]; then
		fstab_spec="UUID=$uuid"
	else
		fstab_spec="$part"
	fi

	# Kernel root= — UUID= needs initramfs; PARTUUID works bare.
	if [ -n "$partuuid" ]; then
		kernel_root="PARTUUID=$partuuid"
	else
		kernel_root="$part"
		warn "No PARTUUID — kernel will boot with root=$part"
	fi

	cat > "$dst/etc/fstab" <<EOF
# HUT OS fstab — generated by hut-install
$fstab_spec  /      ext4  defaults,noatime  0  1
proc           /proc  proc  defaults         0  0
sysfs          /sys   sysfs defaults         0  0
devtmpfs       /dev   devtmpfs defaults,mode=0755 0 0
tmpfs          /tmp   tmpfs defaults,nosuid,nodev 0 0
tmpfs          /run   tmpfs defaults,nosuid,nodev,mode=0755 0 0
devpts         /dev/pts devpts defaults,gid=5,mode=620 0 0
EOF

	cat > "$dst/etc/shells" <<EOF
/bin/sh
/bin/ash
/bin/zsh
EOF

	[ -f "$dst/etc/passwd" ] || echo 'root:x:0:0:root:/root:/bin/zsh' > "$dst/etc/passwd"
	[ -f "$dst/etc/group" ] || echo 'root:x:0:' > "$dst/etc/group"
	[ -f "$dst/etc/shadow" ] || echo 'root:*:0:0:99999:7:::' > "$dst/etc/shadow"

	if [ -n "$root_hash" ]; then
		awk -F: -v h="$root_hash" 'BEGIN{OFS=FS} $1=="root"{$2=h} {print}' \
			"$dst/etc/shadow" > "$dst/etc/shadow.new" \
			&& mv "$dst/etc/shadow.new" "$dst/etc/shadow"
	else
		awk -F: 'BEGIN{OFS=FS} $1=="root"{$2=""} {print}' \
			"$dst/etc/shadow" > "$dst/etc/shadow.new" \
			&& mv "$dst/etc/shadow.new" "$dst/etc/shadow"
	fi
	chmod 640 "$dst/etc/shadow" 2>/dev/null || true

	if [ -n "$username" ]; then
		if ! grep -q "^${username}:" "$dst/etc/passwd"; then
			echo "${username}:x:1000:1000:HUT OS User:/home/${username}:/bin/zsh" >> "$dst/etc/passwd"
			grep -q "^${username}:" "$dst/etc/group" \
				|| echo "${username}:x:1000:" >> "$dst/etc/group"
			if [ -n "$user_hash" ]; then
				echo "${username}:${user_hash}:0:0:99999:7:::" >> "$dst/etc/shadow"
			else
				echo "${username}::0:0:99999:7:::" >> "$dst/etc/shadow"
			fi
		fi
		mkdir -p "$dst/home/$username"
		if [ -f "$dst/root/.zshrc" ] && [ ! -f "$dst/home/$username/.zshrc" ]; then
			cp "$dst/root/.zshrc" "$dst/home/$username/.zshrc"
		fi
		if [ -d "$dst/root/.oh-my-zsh" ] && [ ! -e "$dst/home/$username/.oh-my-zsh" ]; then
			ln -sfn /root/.oh-my-zsh "$dst/home/$username/.oh-my-zsh"
		fi
	fi

	mkdir -p "$dst/etc/hutos"
	cat > "$dst/etc/hutos/install-info" <<EOF
installed_by=hut-install
version=$HUTOS_INSTALL_VERSION
hostname=$hostname
fstab_root=$fstab_spec
kernel_root=$kernel_root
EOF

	if [ "${HUTOS_E2E:-0}" = "1" ]; then
		touch "$dst/etc/hutos/selftest-once"
	fi

	ok "Configuration written"
	printf '%s\n' "$kernel_root"
}
